server:
  port: 8082

spring:

  config:
    import: "classpath:/batch-common.yaml"

  application:
    name: job-executor-service

  datasource:
    business:
      jdbc-url: jdbc:postgresql://localhost:5432/job_demo_database
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
        pool-name: Business-Hikari

  # Configuración JPA para el DataSource BBDD
  jpa:
    hibernate:
      ddl-auto: update    # crea/actualiza tablas automáticamente
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

kafka:
  topics:
    job-requests: job-requests-topic
    job-results: job-results-topic

  filter:
    business-domains: ${spring.application.name}
    target-jobs: "ResumenDiarioClientesAsync"     # Solo procesar este
    target-batches: "springBatchSample"         # Solo procesar este

app:
  batch:
    chunk-size: 100
    grid-size: 4
    partition-size: 2000
    mail:
      enabled: false # Cambiar a true cuando configures email
