spring:

  batch:
    job:
      enabled: false  # Para que solo se ejecute un job cuando es invocado, de forma asíncrona o síncrona
    jdbc:
      initialize-schema: always # Crea las tablas BATCH_* la primera vez
    # Configuración del pool
    task:
      execution:
        pool:
          core-size: 10
          max-size: 20
          queue-capacity: 500

  datasource:
    batch:
      jdbc-url: jdbc:postgresql://localhost:5432/spring_batch_db
      username: spring_batch_user
      password: spring_batch_password
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 5
        minimum-idle: 2
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
        pool-name: Batch-Hikari

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: ${spring.application.name}-consumer
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-interval-ms: 300000  # 5 minutos para jobs normales
      # Tiempo para detectar consumidor muerto
      session.timeout.ms: 45000      # 45 segundos (debe ser > 3 * heartbeat)
      # Frecuencia de heartbeats
      heartbeat.interval.ms: 3000    # 3 segundos
      # Máximo de registros por poll
      max.poll.records: 50
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.ad.muface.batch.dto.JobRequest

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


kafka:
  topics:
    job-requests: job-requests-topic
    job-results: job-results-topic
  filter:
    business-domains: ${spring.application.name}

# Logging específico para Kafka
logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka: WARN
    com.ad.muface.batch: DEBUG
