-- src/main/resources/schema.sql
-- Spring ejecutará esto automáticamente al iniciar

-- Eliminar tablas si existen
DROP TABLE IF EXISTS daily_summaries CASCADE;
DROP TABLE IF EXISTS customer_transactions CASCADE;

-- Crear tablas con tipos correctos
CREATE TABLE customer_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id VARCHAR(50) UNIQUE,
    customer_id VARCHAR(50),
    amount DECIMAL(10,2),
    currency VARCHAR(3),
    transaction_date DATE,
    status VARCHAR(20) DEFAULT 'PENDING',
    source_file VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE daily_summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    summary_date DATE,
    customer_id VARCHAR(50),
    total_amount DECIMAL(10,2),
    transaction_count INTEGER,
    currency VARCHAR(3),
    processed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    job_execution_id VARCHAR(100)
);

-- Crear índices
CREATE INDEX idx_customer_transactions_status ON customer_transactions(status);
CREATE INDEX idx_customer_transactions_date ON customer_transactions(transaction_date);
CREATE INDEX idx_daily_summaries_date ON daily_summaries(summary_date);